{% set name = "jpterm" %}
{% set version = "0.2.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 862f6492b9fc050beb9fe4106c9258966d92cf6f619d3397f326adefd0b7a22d

build:
  noarch: python
  number: 0
  entry_points:
    - jpterm = jpterm.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - rich-click >=1.6.0
    - txl ==0.2.15
    - txl-cell ==0.2.13
    - txl-console ==0.2.13
    - txl-editors ==0.2.13
    - txl-file-browser ==0.2.13
    - txl-jpterm ==0.2.13
    - txl-kernel ==0.2.13
    - txl-local-contents ==0.2.13
    - txl-local-terminals ==0.2.13
    - txl-local-kernels ==0.2.13
    - txl-notebook-editor ==0.2.13
    - txl-text-editor ==0.2.13
    - txl-markdown-viewer ==0.2.13
    - txl-terminal ==0.2.13
    - txl-launcher ==0.2.13
    - httpx >=0.23.1

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - jpterm
  commands:
    - jpterm --help

about:
  home: https://github.com/davidbrochart/jpterm
  summary: Jupyter in the terminal
  dev_url: https://github.com/davidbrochart/jpterm
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
