{% set name = "jpterm" %}
{% set version = "0.2.19" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 8115cae93210ed5c6741e86e88d1da346f3a3465cd783a25d78740e33f19045c

build:
  noarch: python
  number: 0
  entry_points:
    - jpterm = jpterm.cli:main
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.10
    - pip
    - hatchling
  run:
    - python >=3.10
    - rich-click >=1.6.0
    - txl =0.2.19
    - txl_cell =0.2.14
    - txl_console =0.2.16
    - txl_editors =0.2.14
    - txl_file_browser =0.2.14
    - txl_image_viewer =0.2.14
    - txl_jpterm =0.2.14
    - txl_kernel =0.2.14
    - txl_local_contents =0.2.14
    - txl_local_terminals =0.2.14
    - txl_local_kernels =0.2.14
    - txl_notebook_editor =0.2.14
    - txl_remote_contents =0.2.14
    - txl_remote_terminals =0.2.14
    - txl_remote_kernels =0.2.14
    - txl_text_editor =0.2.14
    - txl_markdown_viewer =0.2.14
    - txl_terminal =0.2.14
    - txl_launcher =0.2.14
    - txl_widgets =0.2.15

test:
  # `pip check` was disabled, see: https://github.com/conda-forge/staged-recipes/pull/26869
  #
  # requires:
  #   - pip
  # commands:
  #   - pip check
  imports:
    - jpterm
  commands:
    - jpterm --help

about:
  home: https://github.com/davidbrochart/jpterm
  summary: Jupyter in the terminal
  dev_url: https://github.com/davidbrochart/jpterm
  license_file: LICENSE
  license: MIT
  license_family: MIT

extra:
  recipe-maintainers:
    - davidbrochart
